### ISSUE TITLE
Database error when in application answering proccess

### ISSUE THREAD

**Issue by Acemavie234** [JuanDelPueblo/discord-application-bot#1]
Hey, Im about to start making my own bot so I am looking at some others to see how things are done. Everything worked fine I was able to setup forms but when the bot creates the thread after clicking Apply it sends the question I answer it and it sends my answer and then in the consle it shows a database error:

Error
    at Database.<anonymous> (C:\Users\PC NAME\OneDrive\Desktop\discord-application-bot-master\node_modules\sequelize\src\dialects\sqlite\query.js:236:27)
    at C:\Users\PC NAME\OneDrive\Desktop\discord-application-bot-master\node_modules\sequelize\src\dialects\sqlite\query.js:234:50
    at new Promise (<anonymous>)
    at Query.run (C:\Users\PC NAME\OneDrive\Desktop\discord-application-bot-master\node_modules\sequelize\src\dialects\sqlite\query.js:234:12)
    at C:\Users\PC NAME\OneDrive\Desktop\discord-application-bot-master\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SQLiteQueryInterface.insert (C:\Users\PC NAME\OneDrive\Desktop\discord-application-bot-master\node_modules\sequelize\src\dialects\abstract\query-interface.js:795:21)
    at async Answer.save (C:\Users\PC NAME\OneDrive\Desktop\discord-application-bot-master\node_modules\sequelize\src\model.js:4153:35)
    at async Function.create (C:\Users\PC NAME\OneDrive\Desktop\discord-application-bot-master\node_modules\sequelize\src\model.js:2305:12)
    at async Module.execute (file:///C:/Users/PC NAME/OneDrive/Desktop/discord-application-bot-master/src/events/interactionCreate.ts:110:7) {
  name: 'SequelizeForeignKeyConstraintError',
  parent: [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `answers` (`id`,`thread_id`,`question_id`,`answer`) VALUES (NULL,$1,$2,$3);'
  },
  original: [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `answers` (`id`,`thread_id`,`question_id`,`answer`) VALUES (NULL,$1,$2,$3);'
  },
  sql: 'INSERT INTO `answers` (`id`,`thread_id`,`question_id`,`answer`) VALUES (NULL,$1,$2,$3);',
  parameters: {},
  table: undefined,
  fields: undefined,
  value: undefined,
  index: undefined,
  reltype: undefined
}
Anyone knows why this is happening?

**Comment by JuanDelPueblo** [comment]
I manage to reproduce this problem on a fresh start, which is odd since I am fairly sure I tested this bot before I finished development. After some debugging, I found the error was that it was trying to associate the thread_id in the Answer model with the id in Application model instead of thread_id, which mean it would never work. 

After setting thread_id in Application to be the primary key in commit 4afbf4a, this association is fixed and now submitting answers should work and be updated. Let me know if the updated version still doesn't work for you, it may be required to delete the database.sqlite file for it to work again.
